### ISSUE TITLE
Phase 2 CodeGrade Required for Readings & Labs

### ISSUE THREAD

**Issue by jessicavaughn619** [learn-co-curriculum/react-hooks-state#3]
### Canvas Link

https://learning.flatironschool.com/courses/6191/assignments/228661?module_item_id=534008

### Concern

Phase 2 React has CodeGrade attached for every lecture and lab rather than just for the labs. Not a huge deal, but for someone who wants to have their progress reflected accurately in Canvas I have to push up all of the follow along GitHub links to CodeGrade to show the lecture/reading is complete. I think CodeGrade and a submission should only be required for the actual labs, like in phase 1.

**Comment by lizbur10** [comment]
Hi @leopards4life ! This issue has now been corrected, although unfortunately we weren't able to do it retroactively because students would have lost their progress for any lessons they had already submitted through CodeGrade. The fix will be in place for future cohorts, however.

Thanks for contributing to the Flatiron School curriculum and apologies for the inconvenience 💙
